# Generated by Django 5.2.1 on 2025-08-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_number_of_items_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
